group=dev.folia
mcVersion=26.2
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.2
channel=ALPHA

# tessera related build information
tesseraBuildVersion=012
tesseraBuildChannel=stable

# Build Information for dummies
# i am the dummy
# use this -> .\gradlew.bat createPaperclipJar lol

# latest commit from paper - this might be refreshed by us in the future,
#  make sure to create a patch for ServerBuildInfoImpl.java -> rename folia
# paper upstream
#  old upstreams:
#     first build -          # paperRef=2717585e686d7d294cabce9f1753280780ecf847
# https://github.com/PaperMC/Paper/commit/a95ae8d00f4434acb823ba345d249ea084cec785
# Commit from Jul 29, 2026 - Expose reachRange argument in findPath for PathFinder (#13026)
paperRef=a95ae8d00f4434acb823ba345d249ea084cec785

# Commit from Jul 4, 2026 - Update to 26.2
foliaRef=62034198de6d034bed025f34f48e8950b57c77ee

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
